<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Akshay-PC" ignored="0" name="Default test" tests="3" failures="1" timestamp="27 Aug 2017 09:04:54 GMT" time="160.4" errors="0">
  <testcase name="TestA_user_invalid_login_check" time="155.872" classname="Tests.Login.LoginTest">
    <failure type="java.lang.AssertionError" message="
Expecting:
 &amp;lt;&amp;quot;https://s-www.myngconnect.com/login/teacher/login.spr&amp;quot;&amp;gt;
to be equal to:
 &amp;lt;&amp;quot;https://s-www.myngconnect.com/login/teacher/login.spr?login_error=2&amp;quot;&amp;gt;
but was not.">
      <![CDATA[java.lang.AssertionError: 
Expecting:
 <"https://s-www.myngconnect.com/login/teacher/login.spr">
to be equal to:
 <"https://s-www.myngconnect.com/login/teacher/login.spr?login_error=2">
but was not.
	at Tests.Login.LoginTest.TestA_user_invalid_login_check(LoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- TestA_user_invalid_login_check -->
  <testcase name="TestB_user_login_check" time="0.0" classname="Tests.Login.LoginTest">
    <skipped/>
  </testcase> <!-- TestB_user_login_check -->
  <testcase name="TestC_user_logout_check" time="0.0" classname="Tests.Login.LoginTest">
    <skipped/>
  </testcase> <!-- TestC_user_logout_check -->
</testsuite> <!-- Default test -->
